LOGPATH: ./log/IEMOCAP/char
NUM_FOLD: 5
DATA:
  DATASET: IEMOCAP
  DATA_PATH: ./dataset/IEMOCAP/iemocap4char.pkl
  BPE_MODE: char
  SYMBOL_PATH: ./dataset/IEMOCAP/iemocap_char_units.txt
  BPEMODEL_PATH: ./dataset/IEMOCAP/iemocap_bpe5000.model
  BATCH_SIZE: 1
  AUDIO_MAX_LENGTH: 120000
MODEL:
  HEAD_LOSS: ce
  HEAD_WEIGHT: 1.0
  JOINT_LOSS: ce
  JOINT_WEIGHT: 0.0
  LM_WEIGHT: 0.0
  RNNT_WEIGHT: 0.5
  NUM_CLASSES: 4
  VOCAB_SIZE: 31
  PRETRAIN: wav2vec2
  ENCODER:
    ENC_DIM: 768
  PREDICTOR:
    EMBED_DIM: 640
    HIDDEN_DIM: 640
    OUTPUT_DIM: 768
  JOINT:
    JOIN_DIM: 768
    JOINT_MODE: add
    PRE_JOIN: True
    POST_JOIN: False
TRAIN:
  FINETUNE: True
  BASE_LR: 5.0e-06
  EPOCHS: 100
  WARMUP_EPOCHS: 20
  WARMUP_LR: 5.0e-07
  WEIGHT_DECAY: 0.05
  OPTIMIZER:
    NAME: adam
  LR_SCHEDULER:
    DECAY_EPOCHS: 50
    DECAY_RATE: 0.1
    NAME: lambda